services:
  saplsserver:
    container_name: saplsserver
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "7211:7211"
      - "7212:7212"
    environment:
      - DOTNET_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:7211
    networks:
      - app-network

networks:
  app-network:
    driver: bridge